
version: '3.8'

services:
  mongodb:
    image: mongo:7.0.5-rc0
    container_name: mongodb-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
  redis:
    image: redis:7.0.14
    container_name: redis-container
    ports:
      - "6379:6379"
  mysql:
    image: mysql:8.2.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: TripConnect
      MYSQL_USER: service
      MYSQL_PASSWORD: service
    ports:
      - "3306:3306"
