version: '3.8'

services:
  mongodb:
      image: mongo:7.0.5-rc0
      container_name: mongodb-container
      ports:
        - "27017:27017"
      environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: admin
  redis:
    image: redis:7.0.14
    container_name: redis-container
    ports:
      - "6379:6379"
